version: '2'
services:
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluent-bit
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  fluent-bit:
    image: fluent/fluent-bit:1.5
    volumes:
      - ./conf:/fluent-bit/etc
    ports:
      - 24224:24224
      - 24224:24224/udp
    networks:
      - elastic
