filebeat.inputs:
  - input_type: log
    paths:
      - /logs/*.log
    json.message_key: event
    json.keys_under_root: true
    json.overwrite_keys: true


setup.kibana:
  host: "http://kibana:5601"

output.elasticsearch:
  hosts: ['http://elasticsearch:9200']
