version: '3'
services:  

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=hbZkzny5xrvVH
      - POSTGRES_USER=bip
      - POSTGRES_DB=bipgit

  pgbouncer:
    image: edoburu/pgbouncer
    environment:
       - DB_USER=bip
       - DB_PASSWORD=hbZkzny5xrvVH
       - DB_HOST=db
       - DB_NAME=bipgit 
       - POOL_MODE=transaction
       - ADMIN_USERS=postgres,bip
    ports:
      - "5432:5432"
    depends_on:
      - db

volumes:
  pg_data: